import Color from '../../SkyblockUtilities/enums/Color';

const ModuleName = 'Hackboxes';
const Version = JSON.parse(FileLib.read(`${Config.modulesFolder}/${ModuleName}/metadata.json`)).version;
const CategoryDescription = `${Color.GREEN}${ModuleName} ${Color.GRAY}v${Version} by ${Color.GOLD}Steinente ${Color.GRAY}/ ${Color.GOLD}EnteStein`;

const Setting = {
    ModuleName: ModuleName,
    Version: Version,
    CategoryDescription: CategoryDescription,
    General: 'General',
    SubGeneral: ' General ',
    Updates: 'Updates',
    Open: 'Open',
    Areas: 'Areas',
    SpecificPlaceDescription: 'Creates borders around significant entities at the specific place',
    Everywhere: 'Everywhere',
    Hub: 'Hub',
    Park: 'The Park',
    SpidersDen: 'Spider\'s Den',
    End: 'The End',
    DwarvenMines: 'Dwarven Mines',
    FarmingIslands: 'The Farming Islands',
    Dungeon: 'Dungeon',
    Misc: 'Misc',
    Special: 'Special',
    Slayer: 'Slayer',
    Mythological: 'Mythological Ritual',
    Event: 'Event',
    Boss: 'Boss',
    Enabled: 'Enabled',
    ThroughWall: 'Through Wall',
    Color: 'Color',
    RGB: 'RGB',
    Gift: 'Gift',
    Jerry: 'Jerry',
    Revenant: 'Revenant Horror',
    AtonedRev: 'Atoned Revenant',
    AtonedChamp: 'Atoned Champion',
    Deformed: 'Deformed Revenant',
    Champ: 'Revenant Champion',
    Sycophant: 'Revenant Sycophant',
    Rat: 'Rat',
    Inquisitor: 'Minos Inquisitor',
    Packmaster: 'Sven Packmaster',
    Alpha: 'Sven Alpha',
    Follower: 'Sven Follower',
    Enforcer: 'Pack Enforcer',
    Father: 'Broodfather',
    Mutant: 'Mutant Tarantula',
    Beast: 'Tarantula Beast',
    Vermin: 'Tarantula Vermin',
    Keeper: 'Arachne\'s Keeper',
    Mother: 'Brood Mother',
    Brood: 'Arachne\'s Brood',
    Arachne: 'Arachne',
    Eye: 'Summoning Eye',
    Zealot: 'Special Zealot',
    Seraph: 'Voidgloom Seraph',
    Glyph: 'Glyph',
    Devotee: 'Voidling Devotee',
    Dragon: 'Ender Dragon',
    Crystal: 'Ender Crystal',
    PowderGhast: 'Powder Ghast',
    Superprotectron: 'Superprotectron',
    Arrow: 'Arrow',
    Ghost: 'Ghost',
    Trevor: 'Trevor Animal',
    Bonzo: 'Bonzo',
    Livid: 'Livid',
    Bat: 'Bat',
    Fels: 'Fels',
    RequiredMobs: 'Required Mobs'
}
export { Setting as default };